#!/bin/bash
# Customer: thanhtd@matbao.com
# version: 20230828
#set -ex
# chay tam update image nho bo ra
echo "search mbpbx.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.96.0.10
nameserver 8.8.8.8
nameserver 1.1.1.1
options ndots:5" | sudo tee /etc/resolv.conf > /dev/null
# ###################################################################
FLANNEL_GW=$(ip route | grep '^default' | grep 'eth0' | awk '{print $3}')
# ip route add 10.244.0.0/16 via $FLANNEL_GW dev eth0
route del -net 10.244.0.0/16 ; route add -net 10.244.0.0/16 gw $FLANNEL_GW dev eth0
route del -net 10.96.0.0/16 ; route add -net 10.96.0.0/16 gw $FLANNEL_GW dev eth0
# route del -net 103.15.49.0/24 ; route add -net 103.15.49.0/24 dev eth0
route del -net 0.0.0.0 dev eth0
# config iptables
cat > rule << 'EOF'
# Generated by iptables-save v1.8.5 on Tue Apr 16 06:28:54 2024
*filter
:INPUT ACCEPT [1798:627023]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [3604:2047148]
:f2b-asterisk-tcp - [0:0]
:f2b-asterisk-udp - [0:0]
-A INPUT -i net1 -p tcp --dport 22 -j DROP
-A INPUT -p udp -j f2b-asterisk-udp
-A INPUT -p tcp -j f2b-asterisk-tcp
-A f2b-asterisk-tcp -s 2.57.0.0/16 -j REJECT --reject-with icmp-port-unreachable
-A f2b-asterisk-tcp -s 198.204.0.0/16 -j REJECT --reject-with icmp-port-unreachable
-A f2b-asterisk-tcp -s 45.95.0.0/16 -j REJECT --reject-with icmp-port-unreachable
-A f2b-asterisk-tcp -j RETURN
-A f2b-asterisk-udp -s 2.57.0.0/16 -j REJECT --reject-with icmp-port-unreachable
-A f2b-asterisk-udp -s 198.204.0.0/16 -j REJECT --reject-with icmp-port-unreachable
-A f2b-asterisk-udp -j RETURN
COMMIT
# Completed on Tue Apr 16 06:28:54 2024
# 198.204.245.242 21.04.2024
# -A f2b-asterisk-tcp -s 14.191.0.0/16 -j REJECT --reject-with icmp-port-unreachable
# -A f2b-asterisk-udp -s 14.191.0.0/16 -j REJECT --reject-with icmp-port-unreachable
EOF
iptables-restore < rule
