#!/bin/bash
# Customer: thanhtd@matbao.com
# version: 20230828
#set -ex
route del -net 10.244.0.0/16 ; route add -net 10.244.0.0/16 dev eth0
route del -net 103.15.49.0/24 ; route add -net 103.15.49.0/24 dev eth0
route del -net 0.0.0.0 dev eth0
# config iptables
cat > rule << 'EOF'
# Generated by iptables-save v1.8.5 on Tue Apr 16 06:28:54 2024
*filter
:INPUT ACCEPT [1798:627023]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [3604:2047148]
:f2b-asterisk-tcp - [0:0]
:f2b-asterisk-udp - [0:0]
-A INPUT -p udp -j f2b-asterisk-udp
-A INPUT -p tcp -j f2b-asterisk-tcp
-A f2b-asterisk-tcp -s 2.57.0.0/16 -j REJECT --reject-with icmp-port-unreachable
-A f2b-asterisk-tcp -s 198.204.0.0/16 -j REJECT --reject-with icmp-port-unreachable
-A f2b-asterisk-tcp -j RETURN
-A f2b-asterisk-udp -s 2.57.0.0/16 -j REJECT --reject-with icmp-port-unreachable
-A f2b-asterisk-udp -s 198.204.0.0/16 -j REJECT --reject-with icmp-port-unreachable
-A f2b-asterisk-udp -j RETURN
COMMIT
# Completed on Tue Apr 16 06:28:54 2024
# 198.204.245.242 21.04.2024
# -A f2b-asterisk-tcp -s 14.191.0.0/16 -j REJECT --reject-with icmp-port-unreachable
# -A f2b-asterisk-udp -s 14.191.0.0/16 -j REJECT --reject-with icmp-port-unreachable
EOF
iptables-restore < rule
